FROM apache/airflow:2.8.1

# Switch to root to install system packages
USER root

# Install compiler for DuckDB + tools for MinIO CLI
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        build-essential \
        curl \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Install MinIO CLI (mc)
RUN curl -O https://dl.min.io/client/mc/release/linux-amd64/mc && \
    chmod +x mc && \
    mv mc /usr/local/bin/mc

# Switch back to airflow user
USER airflow

# Install Python packages
RUN pip install --no-cache-dir \
        pyiceberg[pyarrow] \
        pyarrow \
        duckdb==1.1.0 \
        minio \
        clickhouse-connect==0.6.5

