version: 2


models:
  - name: fact_people_traffic
    description: "Fact table of people traffic"
    columns:
      - name: PeopleTraffic
        description: "Unique identifier"
        tests:
          - not_null
      - name: DateKey
        description: "Reference to the date dimension"
        tests:
          - not_null
      - name: TimeKey
        description: "Reference to the time dimension"
        tests:
          - not_null
      - name: BuildingKey
        description: "Reference to the building dimension"
        tests:
          - not_null
      - name: WeatherKey
        description: "Reference to the weather dimension"
        tests:
          - not_null
      - name: people_in
        description: "Incoming people"
        tests:
          - not_null
      - name: people_out
        description: "Outgoing people"
        tests:
          - not_null
      - name: PeopleTrafficAmount
        description: "Total amount of people"
        tests:
          - not_null
      - name: FullDate
        description: "Date"
        tests:
          - not_null
