version: 2

sources:
  - name: 'staging_data'
    description: Raw data
    database: default
    # schema: peopletraffic
    # schema: default
    tables:
      - name: 'bronze_weather'
      - name: 'bronze_infrared'

      # - name: stg_fact_people_traffic
      #   description: Raw people fact data
      # - name: stg_dim_building
      #   description: Raw people data
      # - name: stg_dim_weather
      #   description: Raw weather data
      # - name: stg_dim_date
      #   description: Daytime data
      # - name: stg_dim_time
      #   description: Time data
