version: 2

sources:
  - name: 'bronze_data'  # A group name for your sources
    database: default  # Or your ClickHouse DB name
    
    tables:
      # These names MUST match your CSV filenames
      - name: 'bronze_weather'
      - name: 'bronze_mobility'
      - name: 'bronze_infrared'